Repository soffan-group-25/ci-server, pull requests merged in 2023-02, with the labels that each got.

#11 feat: Add java CI server skeleton
  .gitignore
  app/build.gradle.kts
  app/src/main/java/ciserver/App.java
  app/src/main/java/ciserver/ContinuousIntegrationServer.java
Labels: enhancement

#25 doc: Remove `clang-format` from pr template
  .github/pull_request_template.md
Labels: internal

#23 feat: Add gson package for json parsing
  app/build.gradle.kts
  app/src/main/java/ciserver/ContinuousIntegrationServer.java
Labels: enhancement

#27 feat: Add PushEvent datastructure
  app/src/main/java/ciserver/ContinuousIntegrationServer.java
  app/src/main/java/ciserver/PushEvent.java
  app/src/test/java/ciserver/PushEventTest.java
Labels: enhancement

#33 doc: Add chore prefix to pr template
  .github/pull_request_template.md
Labels: documentation

#29 chore: Add pipeline class
  app/src/main/java/ciserver/Pipeline.java
  app/src/test/java/ciserver/PipelineTest.java
Labels: enhancement

#40 feat: Add the ability to send HTTP POST requests
  app/src/main/java/ciserver/ContinuousIntegrationServer.java
  app/src/main/java/ciserver/PipelineUpdateRequest.java
  app/src/test/java/ciserver/PipelineUpdateRequestTest.java
Labels: dev

#36 feat: Add pulling repository
  .gitignore
  app/build.gradle.kts
  app/src/main/java/ciserver/Pipeline.java
  app/src/main/java/ciserver/PipelinePuller.java
  app/src/main/java/ciserver/PushEvent.java
  app/src/main/resources/log4j.properties
  app/src/test/java/ciserver/PipelinePullerTest.java
  app/src/test/java/ciserver/PipelineTest.java
  app/src/test/java/ciserver/PushEventTest.java
Labels: enhancement

#46 fix: Set manifest of built jar
  app/build.gradle.kts
Labels: bug, dev

#37 feat: Add compiling cababilities
  app/src/main/java/ciserver/Pipeline.java
  app/src/main/java/ciserver/PipelineCompiler.java
  app/src/test/java/ciserver/PipelineCompilerTest.java
Labels: enhancement

#50 feat: Add observer interface to pipeline
  app/src/main/java/ciserver/Pipeline.java
  app/src/main/java/ciserver/PipelineCompiler.java
  app/src/main/java/ciserver/PipelinePuller.java
  app/src/test/java/ciserver/PipelineCompilerTest.java
  app/src/test/java/ciserver/PipelinePullerTest.java
  app/src/test/java/ciserver/PipelineTest.java
Labels: enhancement

#56 feat: Add doing CI before sending status report to github
  .gitignore
  app/src/main/java/ciserver/ContinuousIntegrationServer.java
  app/src/main/java/ciserver/Pipeline.java
  app/src/main/java/ciserver/PipelineCompiler.java
  app/src/main/java/ciserver/PipelineUpdateRequest.java
  app/src/test/java/ciserver/ContinuousIntegrationServerTest.java
  app/src/test/java/ciserver/PipelineCompilerTest.java
  app/src/test/java/ciserver/PipelineTest.java
  app/src/test/java/ciserver/PipelineUpdateRequestTest.java
Labels: enhancement, Requirement

#72 feat: Add testing build in CI
  app/src/main/java/ciserver/Pipeline.java
  app/src/main/java/ciserver/PipelineCommandExecuter.java
  app/src/test/java/ciserver/ContinuousIntegrationServerTest.java
  app/src/test/java/ciserver/PipelineCompilerTest.java
  app/src/test/java/ciserver/PipelineTest.java
Labels: enhancement, Requirement

#76 feat: Add status updating to github after each pipeline step
  app/src/main/java/ciserver/ContinuousIntegrationServer.java
Labels: enhancement, Remarkable

#69 Doc: added essence team documentation
  Essence.md
  README.md
Labels: documentation

#79 feat: Add web log functionality
  README.md
  app/src/main/java/ciserver/ContinuousIntegrationServer.java
  app/src/main/java/ciserver/Pipeline.java
  app/src/main/java/ciserver/PipelineCommandExecuter.java
  app/src/main/java/ciserver/PipelinePuller.java
  app/src/main/java/ciserver/PushEvent.java
  app/src/test/java/ciserver/ContinuousIntegrationServerTest.java
  app/src/test/java/ciserver/PipelinePullerTest.java
  app/src/test/java/ciserver/PipelineTest.java
Labels: enhancement, Remarkable
